

name: Script Runner


on:
  workflow_dispatch:


jobs:
  runscript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run the script
        run: ./twarcscript.sh
