

name: Script Runner


on:
  workflow_dispatch:


jobs:
  runscript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Run the script
        run: |
          chmod -R 777 .
          ls -a
          pip install --upgrade twarc
          bash twarcscript.sh
